name: Daily Android Kit Cron

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow to be called from a workflow child  
  workflow_call: 

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: "Clean up old branches"
    steps:
      - name: "Delete stale branches"
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        id: delete
        with:
          github_token: ${{ secrets.MP_INTEGRATIONS_SEMANTIC_RELEASE_BOT }}
          last_commit_age_days: 30

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete.outputs.deleted_branches }}'"