name: Daily Cron

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow to be called from a workflow child  
  workflow_call:

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: "Clean up old branches"
    steps:
      - name: "Delete stale branches"
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v2
        id: delete
        with:
          github_token: ${{ secrets.MP_DAILY_CRON_BOT }}
          last_commit_age_days: 30

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete.outputs.deleted_branches }}'"

  run-semgrep-full:
    name: "Run Semgrep over entire repo"
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Run Semgrep"
        run: "semgrep --config=auto ."

  regression-check:
    name: "Run regression"
    if: contains(github.repository, 'android')
    uses: mParticle/mparticle-workflows/.github/workflows/android-kit-push.yml@main
    with:
      dryRun: "true"
      branch_name: "development"
    secrets: inherit

