name: Daily Cron

on:
  # Run daily at midnight
  schedule:
    - cron: "0 0 * * *"

  # Allow to be called from a workflow child  
  workflow_call: 
    secrets:
      MP_DAILY_CRON_BOT:
        description: 'token needed for stale action'
        required: true

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    name: "Clean up old branches"
    steps:
      - name: "Delete stale branches"
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        id: delete
        with:
          github_token: ${{ secrets.MP_DAILY_CRON_BOT }}
          last_commit_age_days: 30

          # Disable dry run and actually get stuff deleted
          dry_run: no

      - name: Get output
        run: "echo 'Deleted branches: ${{ steps.delete.outputs.deleted_branches }}'"

  run-semgrep-full:
    name: "Run Semgrep over entire repo"
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Get Semgrep configs"
        run: |
          REPO_NAME=${{ github.event.repository.name }}

          if [[ $REPO_NAME =~ "android" ]]; then
              echo "SEMGREP_RULES=p/java p/kotlin p/javascript r/bash r/yaml" >> $GITHUB_ENV
          elif [[ $REPO_NAME =~ "apple" ]]; then
              echo "SEMGREP_RULES=p/ci p/javascript p/ruby r/bash r/yaml" >> $GITHUB_ENV
          elif [[ $REPO_NAME =~ "web" || $REPO_NAME =~ "node" ]]; then
              echo "SEMGREP_RULES=p/javascript p/typescript" >> $GITHUB_ENV
          else
              echo "SEMGREP_RULES=auto" >> $GITHUB_ENV
          fi

      - name: "Run Semgrep"
        run: "semgrep --config=${{ env.SEMGREP_RULES}} ."
