name: "Dependabot Branch Rebase"

on: [ workflow_call ]

jobs:
  rebase-branch:
    name: "Rebase development onto chore/dependabot Branch"
    env:
      GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mparticle-automation
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-automation
      GIT_COMMITTER_EMAIL: developers@mparticle.com
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout development branch"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
          ref: development
          fetch-depth: 0
      - name: "Import GPG Key"
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: "Rebase chore/dependabot branch"
        run: |
          git fetch origin chore/dependabot
          git checkout chore/dependabot
          git rebase development
          git push -f origin HEAD:chore/dependabot
