name: "Static analysis checks for security vulnerabilities"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-semgrep:
    name: "Run Semgrep to find vulnerabilities and security antipatterns"
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep-action
    if: |
      github.actor != 'dependabot[bot]' &&
      ( contains(github.event.repository.name, 'android') || contains(github.event.repository.name, 'apple') )
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Determine base branch"
        run: |
          # NOTE: This is a temporary measure in light of https://github.com/actions/runner/issues/2033
          git config --global --add safe.directory $(pwd)

          echo $(pwd)
          echo $(git status)

          if [[ -n $(git branch --list main) ]]; then
              echo "SEMGREP_BASELINE_REF=main" >> $GITHUB_ENV
          elif [[ -n $(git branch --list master) ]]; then
              echo "SEMGREP_BASELINE_REF=master" >> $GITHUB_ENV
          else
              echo "Could not find either main or master branch! Defaulting to HEAD^"
              echo "SEMGREP_BASELINE_REF=HEAD^" >> $GITHUB_ENV
          fi

      - name: "Determine which Semgrep config(s) to use"
        run: |
          REPO_NAME=${{ github.event.repository.name }}

          if [[ $REPO_NAME =~ "/android/" ]]; then
              SEMGREP_RULES="p/java p/kotlin p/javascript r/bash r/yaml"
          elif [[ $REPO_NAME =~ "/apple/" ]]; then
              SEMGREP_RULES="p/ci p/javascript p/ruby r/bash r/yaml"
          elif [[ $REPO_NAME =~ "/web/" || $REPO_NAME =~ "/node/" ]]; then
              SEMGREP_RULES="p/javascript p/typescript"
          else
              SEMGREP_RULES="auto"
          fi

          echo "SEMGREP_RULES=$SEMGREP_RULES" >> $GITHUB_ENV
          echo "Setting SEMGREP_RULES to \'$SEMGREP_RULES\'"

      - name: "Run Semgrep"
        run: "semgrep ci"
        env:
          SEMGREP_RULES: ${{ env.SEMGREP_RULES }}
          SEMGREP_BASELINE_REF: ${{ env.SEMGREP_BASELINE_REF }}  # enables diff-aware scans

  run-mobsfscan:
    name: "Run mobsfscan to find Android/iOS vulnerabilities and misconfigurations"
    runs-on: ubuntu-latest
    if: |
      github.actor != 'dependabot[bot]' &&
      ( contains(github.event.repository.name, 'android') || contains(github.event.repository.name, 'apple'))
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Run mobsfscan"
        uses: MobSF/mobsfscan@main
        with:
          args: '. --sonarqube'
