name: "SonarCloud Check"

on:
  workflow_call:
    inputs:
      app_relative_path:
        description: 'repo path for sample app'
        required: false
        default: "./"
        type: string

jobs:
  sonarcloud-check:
    name: "SonarCloud Check"
    env:
      GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
      GIT_AUTHOR_NAME: mparticle-automation
      GIT_AUTHOR_EMAIL: developers@mparticle.com
      GIT_COMMITTER_NAME: mparticle-automation
      GIT_COMMITTER_EMAIL: developers@mparticle.com
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
          submodules: recursive
      - name: "Set up JDK 11"
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "zulu"
          cache: "gradle"
      - name: "Cache SonarCloud packages"
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: "Cache Gradle packages"
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: "Build and analyze"
        working-directory: ${{ inputs.app_relative_path }}
        run: ./gradlew sonarqube --info
